# https://docs.travis-ci.com/user/customizing-the-build/
# https://docs.travis-ci.com/user/reference/bionic/
# https://docs.travis-ci.com/user/languages/go/
# https://docs.travis-ci.com/user/deployment/pages/

dist: bionic

# before_install
# install - install any dependencies required
install:
    - sudo apt-get install hugo

before_script:
    - rm -rf public 2> /dev/null

# script - run the build script
script:
    - hugo 2> /dev/null
    - echo "$CNAME_URL" > public/CNAME

after_success:
    - bash ./Telegram_bot_alarm.sh "success"

after_failure:
    - bash ./Telegram_bot_alarm.sh "failure"

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    email: $GITHUB_EMAIL
    name: $GITHUB_USERNAME
    verbose: true
    keep-history: true
    local-dir: public
    target_branch: master
    on:
        branch: src
